services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file: ./backend/.env  # Load environment variables
    volumes:
      - ./backend:/app  # Sync code changes for development
      - /app/node_modules  # Prevent overwriting node_modules
    depends_on:
      db:
        condition: service_healthy  # Ensure DB is actually ready

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  # Syncs local frontend code with container
      - /app/node_modules  # Prevents overwriting node_modules
    depends_on:
      - backend

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # Add health check for PostgreSQL readiness
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
